Improve file documentation
buildingSMART/BCF-API pull request #271
Opened 2021-03-16 10:13 UTC by jasollien

2021-03-16 10:13 UTC, jasollien commented
https://github.com/buildingSMART/BCF-API/issues/269

2021-03-16 14:35 UTC, GeorgDangl approved these changes

2021-03-22 07:25 UTC, GeorgDangl requested changes

2021-03-22 07:25 UTC, GeorgDangl commented on README.md
> +Update a **collection** of file references on the topic header. This operation is only possible when the server returns the `updateFiles` flag in the Topic authorization, see section [3.2.8](#328-det
Typo, missing an `a` in `[files_informtion]`

2021-03-23 19:40 UTC, GeorgDangl approved these changes

2021-03-29 09:52 UTC, merged